from .node_nsfw_prompt_generator import (
    NODE_CLASS_MAPPINGS as _GEN_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _GEN_DISPLAY,
)
from .node_image_describer import (
    NODE_CLASS_MAPPINGS as _DESC_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _DESC_DISPLAY,
)
from .node_grok_api_image_describer import (
    NODE_CLASS_MAPPINGS as _GROK_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _GROK_DISPLAY,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_GEN_CLASS)
NODE_CLASS_MAPPINGS.update(_DESC_CLASS)
NODE_CLASS_MAPPINGS.update(_GROK_CLASS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_GEN_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(_DESC_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(_GROK_DISPLAY)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
